### ISSUE TITLE
When will task2 test data be released?

### ISSUE THREAD

**Issue by Chucy2020** [amazon-science/dstc11-track2-intent-induction#14]
Hello, excuse me, Where is task2's test set?  and when will the test data of task2 be released?

Thanks

**Comment by jgung** [comment]
Hi @Chucy2020, thanks for your question! We will release the Task 2 `test-utterances.jsonl` files after the testing phase ends. Only the induced intent schema (see the [Task 2 description](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md)) should be submitted for this task.

Task 1 and Task 2 use the same input conversations (although for Task 2, only the provided "InformIntent" dialogue act predictions should be used rather than the input turns with dummy labels provided for Task 1). I hope that helps!

**Comment by Chucy2020** [comment]
> Hi @Chucy2020, thanks for your question! We will release the Task 2 `test-utterances.jsonl` files after the testing phase ends. Only the induced intent schema (see the [Task 2 description](https://github.com/amazon-research/dstc11-track2-intent-induction/blob/main/dstc11/task2-open-intent-induction.md)) should be submitted for this task.
> 
> Task 1 and Task 2 use the same input conversations (although for Task 2, only the provided "InformIntent" dialogue act predictions should be used rather than the input turns with dummy labels provided for Task 1). I hope that helps!

ok, i got it. thanks.

In other words, during the task2 evaluation phase, you will use our submitted clustering data (intent schema) to train your own classifier(LogisticRegression) and then use it to test the results on the test set, right?

It may be our misunderstanding. according to the codes you provided (the picture is down here), we mistakenly thought that the classifier could be selected by ourselves, so we did some work on the classifier, but it doesn't matter, the LogisticRegression classifier has worked very well.

Thank you for your patience and prompt reply

![image](https://user-images.githubusercontent.com/73978694/192915374-572336bf-ce62-4759-8492-4d98ac923d79.png)

**Comment by jgung** [comment]
> In other words, during the task2 evaluation phase, you will use our submitted clustering data (intent schema) to train your own classifier(LogisticRegression) and then use it to test the results on the test set, right?

That's correct. Since the focus of this task is to evaluate intent schema induction rather than the intent classification approach, this part of the evaluation is kept fixed across all participants.

> we mistakenly thought that the classifier could be selected by ourselves, so we did some work on the classifier, but it doesn't matter, the LogisticRegression classifier has worked very well.

Sorry for the misunderstanding on this! If you decide to submit a system paper to the workshop, you are certainly free to include experiments with different classifier variants.
